version: 2
updates:
  # DÃ©pendances Composer (PHP)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      open-pull-request-limit: 10
      reviewers:
      - "thomas-thony"
    labels:
      - "dependencies"
      - "composer"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"