- name: Update composer.lock
  run: composer update --lock --no-scripts --no-install
  
- name: Commit composer.lock
  run: |
    git config user.name "GitHub Actions"
    git config user.email "actions@github.com"
    git add composer.lock
    git commit -m "Update composer.lock" || true
    git push